package net.soivi.todo;

import com.vaadin.addon.touchkit.extensions.TouchKitIcon;
import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.addon.touchkit.ui.Switch;
import com.vaadin.addon.touchkit.ui.VerticalComponentGroup;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

public class EditTodoView extends NavigationView {
	final VerticalComponentGroup content = new VerticalComponentGroup();
	TodoList publicTodoList = new TodoList("");
	static String view = "all";
	
	public EditTodoView(TodoList todoList) {
		publicTodoList = todoList;
		setCaption(publicTodoList.getListname());
		updatelist();
		
		setContent(content);
	}
	
	public void changeView(String changeView) {
		view = changeView;
	}
	
	public void updatelist(){
		content.removeAllComponents();
		
		HorizontalLayout hcontent = new HorizontalLayout ();
		
		final TextField txf = new TextField();
		txf.setInputPrompt("New List");
		Button addButton = new Button("Add");
		TouchKitIcon.plusSign.addTo(addButton);
		addButton.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(ClickEvent event) {
            	publicTodoList.addTodo(new Todo(txf.getValue()));
            	updatelist();
            }
        });
		hcontent.addComponent(addButton);
		hcontent.addComponent(txf);
		
		content.addComponent(hcontent);
		
		
		for (int i = 0; i < publicTodoList.getSize(); i++) {
			final Todo todo = publicTodoList.getTodo(i);
			if(view == "all" || view == "todo" && !todo.isDone() || view =="checked" && todo.isDone()) {
			Switch button = new Switch(todo.getTitle(), todo.isDone());

			button.addValueChangeListener(new ValueChangeListener() {
				@Override
				public void valueChange(ValueChangeEvent event) {
					if(todo.isDone()) {
						todo.setDone(false);
					} else {
						todo.setDone(true);
					}
					updatelist();
				}
			});
			content.addComponent(button);
			}
		}
	}
}
