package com.example.tokka;

import java.util.ArrayList;

import com.vaadin.addon.touchkit.extensions.TouchKitIcon;
import com.vaadin.addon.touchkit.ui.NavigationButton;
import com.vaadin.addon.touchkit.ui.NavigationButton.NavigationButtonClickEvent;
import com.vaadin.addon.touchkit.ui.NavigationButton.NavigationButtonClickListener;
import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.addon.touchkit.ui.VerticalComponentGroup;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class EditListView extends NavigationView {
	final VerticalComponentGroup content = new VerticalComponentGroup();

	public EditListView() {
		setCaption("Edit List");
		
		updatelist();

		
		setContent(content);
	}
	
	public void updatelist() {
		content.removeAllComponents();
		HorizontalLayout hcontent = new HorizontalLayout ();
		
		final TextField txf = new TextField();
		txf.setInputPrompt("New List");
		Button addButton = new Button("Add");
		TouchKitIcon.plusSign.addTo(addButton);
		addButton.addClickListener(new ClickListener() {
            @Override
            public void buttonClick(ClickEvent event) {
            	TodoManager.addNewTodoList(txf.getValue());
            	updatelist();
            }
        });
		hcontent.addComponent(addButton);
		hcontent.addComponent(txf);
		
		content.addComponent(hcontent);

		ArrayList<TodoList> todolists = TodoManager.getTodoLists();
		
		for (int i = 0; i < todolists.size(); i++) {
			final int e = i;
			TodoList todoList = todolists.get(i);
			Button button = new Button(todoList.getListname());
			TouchKitIcon.removeSign.addTo(button);
			content.addComponent(button);
			button.addClickListener(new ClickListener() {
				@Override
				public void buttonClick(ClickEvent event) {
					TodoManager.removeTodoList(e);
					updatelist();
				}
			});
		}
	}
}
